services:
  master:
    build:
      context: .
      target: master
    volumes:
      - multipaper-world:/MultiPaper/world
      - multipaper-world_nether:/MultiPaper/world_nether
      - multipaper-world_the_end:/MultiPaper/world_the_end
    ports:
      - "25565:25565"

  paperclip:
    build:
      context: .
      target: paperclip

volumes:
  multipaper-world:
  multipaper-world_nether:
  multipaper-world_the_end:
